name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'temurin'
      architecture: x64
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.0
      with:
        # Install just one or all simultaneously
        # The value must indicate a particular version of the tool, or use 'latest'
        # to always provision the latest version
        cli: 1.12.0                  # Clojure CLI based on tools.deps
        lein: 2.9.1                  # Leiningen
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
